// fork.go — /fork command.
//
// /fork creates a branch summary entry at the current leaf and switches
// the leaf to the start of the new branch. The summary is generated by
// the configured summarizer; if no summarizer is available, /fork
// falls back to a plain Branch (no summary).
package slash

import (
	"context"
	"errors"
	"fmt"

	"github.com/coevin/tau/internal/agent"
)

type forkCommand struct{}

func newForkCommand() Command { return forkCommand{} }

func (forkCommand) Name() string { return "/fork" }
func (forkCommand) ShortHelp() string {
	return "Branch the session at the current leaf, preserving a summary of the abandoned path"
}

func (forkCommand) Execute(ctx context.Context, args string, session agent.CommandSession) (string, error) {
	if session == nil {
		return "", errors.New("/fork: session is nil")
	}
	rt := session.Runtime()
	leafID := rt.State().LeafID()
	if leafID == "" {
		return "", errors.New("/fork: no entries to fork from (session is empty)")
	}
	// The lazy manager materializes a synthetic SessionHeader root at
	// Create time, so LeafID is non-empty even on a fresh session. Detect
	// "empty" by checking the tree length: only the root means nothing
	// meaningful to fork from.
	if tree, err := rt.State().Tree(); err == nil && tree.Len() <= 1 {
		return "", errors.New("/fork: no entries to fork from (session is empty)")
	}

	newID, err := rt.State().BranchWithSummary(ctx, leafID, summarizerClient(session))
	if err != nil {
		// Two known cases:
		// 1. BranchWithSummary is not wired on this Manager
		//    (ErrBranchWithSummaryUnsupported). Fall back to plain Branch.
		// 2. Real failure (LLM error, ctx cancelled). Surface to user.
		if isUnsupported(err) {
			if branchErr := rt.State().Branch(leafID); branchErr != nil {
				return "", fmt.Errorf("/fork: branch fallback: %w", branchErr)
			}
			return fmt.Sprintf("forked at %s (no summary; summarizer unavailable)", leafID), nil
		}
		return "", fmt.Errorf("/fork: %w", err)
	}
	return fmt.Sprintf("forked at %s; new branch leaf=%s", leafID, newID), nil
}
