// Plugin protocol for tau. Defines the gRPC contract between the tau host
// (this Go module) and external plugin processes (standalone Go binaries
// built via go-plugin).
//
// The host acts as gRPC client for the Plugin service; the plugin acts as
// gRPC server for Plugin. The plugin acts as gRPC client for the Host
// service; the host acts as gRPC server for Host. go-plugin negotiates the
// bidirectional connection over a single anonymous Unix-domain socket.
//
// Code generation: see the `proto` target in ../../Makefile. Generated
// *.pb.go and *_grpc.pb.go files are committed so consumers do not need a
// working `protoc` to build tau.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: internal/proto/plugin.proto

package tauplugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogRequest_Level int32

const (
	LogRequest_LEVEL_UNSPECIFIED LogRequest_Level = 0
	LogRequest_LEVEL_INFO        LogRequest_Level = 1
	LogRequest_LEVEL_WARN        LogRequest_Level = 2
	LogRequest_LEVEL_ERROR       LogRequest_Level = 3
	LogRequest_LEVEL_DEBUG       LogRequest_Level = 4
)

// Enum value maps for LogRequest_Level.
var (
	LogRequest_Level_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "LEVEL_INFO",
		2: "LEVEL_WARN",
		3: "LEVEL_ERROR",
		4: "LEVEL_DEBUG",
	}
	LogRequest_Level_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"LEVEL_INFO":        1,
		"LEVEL_WARN":        2,
		"LEVEL_ERROR":       3,
		"LEVEL_DEBUG":       4,
	}
)

func (x LogRequest_Level) Enum() *LogRequest_Level {
	p := new(LogRequest_Level)
	*p = x
	return p
}

func (x LogRequest_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogRequest_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_plugin_proto_enumTypes[0].Descriptor()
}

func (LogRequest_Level) Type() protoreflect.EnumType {
	return &file_internal_proto_plugin_proto_enumTypes[0]
}

func (x LogRequest_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogRequest_Level.Descriptor instead.
func (LogRequest_Level) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_plugin_proto_rawDescGZIP(), []int{9, 0}
}

// ProtocolVersion is the single source of truth for the wire-format version
// of the plugin protocol. It is announced by the plugin in its Handshake
// response and verified by the host. Bumping this constant is a breaking
// change and requires a tau minor-version bump.
//
// History:
//
//	1 = initial release (this change).
//
// Keep in sync with internal/plugins/handshake.go.
type ProtocolVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolVersion) Reset() {
	*x = ProtocolVersion{}
	mi := &file_internal_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolVersion) ProtoMessage() {}

func (x *ProtocolVersion) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolVersion.ProtoReflect.Descriptor instead.
func (*ProtocolVersion) Descriptor() ([]byte, []int) {
	return file_internal_proto_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *ProtocolVersion) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// ToolSchema is the JSON Schema descriptor a plugin advertises for one of
// its tools. The host merges these with built-in tool schemas and includes
// the union in every LLM Request.Tools.
type ToolSchema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the un-namespaced tool name as the plugin exposes it
	// (e.g. "status" for the git plugin). The host namespaces it as
	// "<plugin>.<name>" when registering with the agent's tool registry.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// description is the model-facing description of the tool's behavior.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// json_schema is the input JSON Schema (draft 2020-12) serialized to a
	// string. Carrying the schema as a string keeps the proto free of a
	// recursive JSON-Schema-as-proto-schema definition and matches the
	// existing internal/tools.Tool.Parameters() shape.
	JsonSchema    string `protobuf:"bytes,3,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolSchema) Reset() {
	*x = ToolSchema{}
	mi := &file_internal_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolSchema) ProtoMessage() {}

func (x *ToolSchema) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolSchema.ProtoReflect.Descriptor instead.
func (*ToolSchema) Descriptor() ([]byte, []int) {
	return file_internal_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ToolSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolSchema) GetJsonSchema() string {
	if x != nil {
		return x.JsonSchema
	}
	return ""
}

// ContentBlock is a polymorphic piece of a tool result. Mirrors the
// internal/tools.ToolResult.Content shape: a list of typed blocks. Exactly
// one variant field is set per block.
type ContentBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Variant:
	//
	//	*ContentBlock_Text
	//	*ContentBlock_Image
	//	*ContentBlock_Json
	Variant       isContentBlock_Variant `protobuf_oneof:"variant"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentBlock) Reset() {
	*x = ContentBlock{}
	mi := &file_internal_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentBlock) ProtoMessage() {}

func (x *ContentBlock) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentBlock.ProtoReflect.Descriptor instead.
func (*ContentBlock) Descriptor() ([]byte, []int) {
	return file_internal_proto_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ContentBlock) GetVariant() isContentBlock_Variant {
	if x != nil {
		return x.Variant
	}
	return nil
}

func (x *ContentBlock) GetText() *TextBlock {
	if x != nil {
		if x, ok := x.Variant.(*ContentBlock_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *ContentBlock) GetImage() *ImageBlock {
	if x != nil {
		if x, ok := x.Variant.(*ContentBlock_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *ContentBlock) GetJson() *JsonBlock {
	if x != nil {
		if x, ok := x.Variant.(*ContentBlock_Json); ok {
			return x.Json
		}
	}
	return nil
}

type isContentBlock_Variant interface {
	isContentBlock_Variant()
}

type ContentBlock_Text struct {
	Text *TextBlock `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type ContentBlock_Image struct {
	Image *ImageBlock `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

type ContentBlock_Json struct {
	Json *JsonBlock `protobuf:"bytes,3,opt,name=json,proto3,oneof"`
}

func (*ContentBlock_Text) isContentBlock_Variant() {}

func (*ContentBlock_Image) isContentBlock_Variant() {}

func (*ContentBlock_Json) isContentBlock_Variant() {}

type TextBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextBlock) Reset() {
	*x = TextBlock{}
	mi := &file_internal_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextBlock) ProtoMessage() {}

func (x *TextBlock) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextBlock.ProtoReflect.Descriptor instead.
func (*TextBlock) Descriptor() ([]byte, []int) {
	return file_internal_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *TextBlock) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ImageBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mime_type is an image MIME type ("image/png", "image/jpeg", etc.).
	MimeType string `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// data is the raw image bytes; the host base64-encodes for transport.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageBlock) Reset() {
	*x = ImageBlock{}
	mi := &file_internal_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageBlock) ProtoMessage() {}

func (x *ImageBlock) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageBlock.ProtoReflect.Descriptor instead.
func (*ImageBlock) Descriptor() ([]byte, []int) {
	return file_internal_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ImageBlock) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ImageBlock) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// JsonBlock carries structured data the host renders as a fenced code block.
type JsonBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// json is the serialized JSON payload.
	Json          string `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonBlock) Reset() {
	*x = JsonBlock{}
	mi := &file_internal_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonBlock) ProtoMessage() {}

func (x *JsonBlock) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonBlock.ProtoReflect.Descriptor instead.
func (*JsonBlock) Descriptor() ([]byte, []int) {
	return file_internal_proto_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *JsonBlock) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

// ToolCall is the host→plugin invocation.
type ToolCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the request identifier assigned by the model. The plugin should
	// not interpret it; it is echoed back in the ToolResult for state-tree
	// bookkeeping.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name is the un-namespaced tool name as advertised by the plugin.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// args is the raw JSON arguments object from the model. The plugin is
	// responsible for validating it against its declared schema.
	Args []byte `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
	// cwd is the agent's current working directory. The plugin should scope
	// filesystem operations to this directory or below.
	Cwd           string `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_internal_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_internal_proto_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ToolCall) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

// ToolResult is the plugin→host response.
type ToolResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// call_id echoes the ToolCall.id.
	CallId string `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// is_error marks the result as an error. The host surfaces this verbatim
	// in the agent's tool-result message; the model treats it as a failure.
	IsError bool `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	// content is the list of typed content blocks.
	Content       []*ContentBlock `protobuf:"bytes,3,rep,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_internal_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ToolResult) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolResult) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *ToolResult) GetContent() []*ContentBlock {
	if x != nil {
		return x.Content
	}
	return nil
}

// Empty is the conventional empty request/response type.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_proto_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_proto_plugin_proto_rawDescGZIP(), []int{8}
}

// LogRequest is a plugin→host log message.
type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         LogRequest_Level       `protobuf:"varint,1,opt,name=level,proto3,enum=tau.v1.LogRequest_Level" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_internal_proto_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *LogRequest) GetLevel() LogRequest_Level {
	if x != nil {
		return x.Level
	}
	return LogRequest_LEVEL_UNSPECIFIED
}

func (x *LogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// NotifyRequest is a plugin→host user-facing notification. The host routes
// it to its event bus so the TUI / RPC consumer can surface it.
type NotifyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// severity is "info" | "warning" | "error".
	Severity      string `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"`
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_internal_proto_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *NotifyRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *NotifyRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetConfigRequest names a configuration key the plugin wants to read.
type GetConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key is dotted-path (e.g. "compaction.reserveTokens"). Plugins should
	// not read secrets via this RPC; the host redacts known-sensitive keys.
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_internal_proto_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *GetConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// GetConfigResponse carries the resolved value as a string. Empty string +
// found=false means the key was not present.
type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_internal_proto_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *GetConfigResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetConfigResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_internal_proto_plugin_proto protoreflect.FileDescriptor

const file_internal_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/proto/plugin.proto\x12\x06tau.v1\"+\n" +
	"\x0fProtocolVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\"c\n" +
	"\n" +
	"ToolSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vjson_schema\x18\x03 \x01(\tR\n" +
	"jsonSchema\"\x97\x01\n" +
	"\fContentBlock\x12'\n" +
	"\x04text\x18\x01 \x01(\v2\x11.tau.v1.TextBlockH\x00R\x04text\x12*\n" +
	"\x05image\x18\x02 \x01(\v2\x12.tau.v1.ImageBlockH\x00R\x05image\x12'\n" +
	"\x04json\x18\x03 \x01(\v2\x11.tau.v1.JsonBlockH\x00R\x04jsonB\t\n" +
	"\avariant\"\x1f\n" +
	"\tTextBlock\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"=\n" +
	"\n" +
	"ImageBlock\x12\x1b\n" +
	"\tmime_type\x18\x01 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x1f\n" +
	"\tJsonBlock\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\"T\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04args\x18\x03 \x01(\fR\x04args\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\"p\n" +
	"\n" +
	"ToolResult\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError\x12.\n" +
	"\acontent\x18\x03 \x03(\v2\x14.tau.v1.ContentBlockR\acontent\"\a\n" +
	"\x05Empty\"\xb8\x01\n" +
	"\n" +
	"LogRequest\x12.\n" +
	"\x05level\x18\x01 \x01(\x0e2\x18.tau.v1.LogRequest.LevelR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"`\n" +
	"\x05Level\x12\x15\n" +
	"\x11LEVEL_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"LEVEL_INFO\x10\x01\x12\x0e\n" +
	"\n" +
	"LEVEL_WARN\x10\x02\x12\x0f\n" +
	"\vLEVEL_ERROR\x10\x03\x12\x0f\n" +
	"\vLEVEL_DEBUG\x10\x04\"E\n" +
	"\rNotifyRequest\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"$\n" +
	"\x10GetConfigRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"?\n" +
	"\x11GetConfigResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found2\xca\x01\n" +
	"\x06Plugin\x123\n" +
	"\tHandshake\x12\r.tau.v1.Empty\x1a\x17.tau.v1.ProtocolVersion\x120\n" +
	"\tListTools\x12\r.tau.v1.Empty\x1a\x12.tau.v1.ToolSchema0\x01\x12/\n" +
	"\aExecute\x12\x10.tau.v1.ToolCall\x1a\x12.tau.v1.ToolResult\x12(\n" +
	"\bShutdown\x12\r.tau.v1.Empty\x1a\r.tau.v1.Empty2\xa2\x01\n" +
	"\x04Host\x12(\n" +
	"\x03Log\x12\x12.tau.v1.LogRequest\x1a\r.tau.v1.Empty\x12.\n" +
	"\x06Notify\x12\x15.tau.v1.NotifyRequest\x1a\r.tau.v1.Empty\x12@\n" +
	"\tGetConfig\x12\x18.tau.v1.GetConfigRequest\x1a\x19.tau.v1.GetConfigResponseB0Z.github.com/coevin/tau/internal/proto;taupluginb\x06proto3"

var (
	file_internal_proto_plugin_proto_rawDescOnce sync.Once
	file_internal_proto_plugin_proto_rawDescData []byte
)

func file_internal_proto_plugin_proto_rawDescGZIP() []byte {
	file_internal_proto_plugin_proto_rawDescOnce.Do(func() {
		file_internal_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_plugin_proto_rawDesc), len(file_internal_proto_plugin_proto_rawDesc)))
	})
	return file_internal_proto_plugin_proto_rawDescData
}

var file_internal_proto_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_proto_plugin_proto_goTypes = []any{
	(LogRequest_Level)(0),     // 0: tau.v1.LogRequest.Level
	(*ProtocolVersion)(nil),   // 1: tau.v1.ProtocolVersion
	(*ToolSchema)(nil),        // 2: tau.v1.ToolSchema
	(*ContentBlock)(nil),      // 3: tau.v1.ContentBlock
	(*TextBlock)(nil),         // 4: tau.v1.TextBlock
	(*ImageBlock)(nil),        // 5: tau.v1.ImageBlock
	(*JsonBlock)(nil),         // 6: tau.v1.JsonBlock
	(*ToolCall)(nil),          // 7: tau.v1.ToolCall
	(*ToolResult)(nil),        // 8: tau.v1.ToolResult
	(*Empty)(nil),             // 9: tau.v1.Empty
	(*LogRequest)(nil),        // 10: tau.v1.LogRequest
	(*NotifyRequest)(nil),     // 11: tau.v1.NotifyRequest
	(*GetConfigRequest)(nil),  // 12: tau.v1.GetConfigRequest
	(*GetConfigResponse)(nil), // 13: tau.v1.GetConfigResponse
}
var file_internal_proto_plugin_proto_depIdxs = []int32{
	4,  // 0: tau.v1.ContentBlock.text:type_name -> tau.v1.TextBlock
	5,  // 1: tau.v1.ContentBlock.image:type_name -> tau.v1.ImageBlock
	6,  // 2: tau.v1.ContentBlock.json:type_name -> tau.v1.JsonBlock
	3,  // 3: tau.v1.ToolResult.content:type_name -> tau.v1.ContentBlock
	0,  // 4: tau.v1.LogRequest.level:type_name -> tau.v1.LogRequest.Level
	9,  // 5: tau.v1.Plugin.Handshake:input_type -> tau.v1.Empty
	9,  // 6: tau.v1.Plugin.ListTools:input_type -> tau.v1.Empty
	7,  // 7: tau.v1.Plugin.Execute:input_type -> tau.v1.ToolCall
	9,  // 8: tau.v1.Plugin.Shutdown:input_type -> tau.v1.Empty
	10, // 9: tau.v1.Host.Log:input_type -> tau.v1.LogRequest
	11, // 10: tau.v1.Host.Notify:input_type -> tau.v1.NotifyRequest
	12, // 11: tau.v1.Host.GetConfig:input_type -> tau.v1.GetConfigRequest
	1,  // 12: tau.v1.Plugin.Handshake:output_type -> tau.v1.ProtocolVersion
	2,  // 13: tau.v1.Plugin.ListTools:output_type -> tau.v1.ToolSchema
	8,  // 14: tau.v1.Plugin.Execute:output_type -> tau.v1.ToolResult
	9,  // 15: tau.v1.Plugin.Shutdown:output_type -> tau.v1.Empty
	9,  // 16: tau.v1.Host.Log:output_type -> tau.v1.Empty
	9,  // 17: tau.v1.Host.Notify:output_type -> tau.v1.Empty
	13, // 18: tau.v1.Host.GetConfig:output_type -> tau.v1.GetConfigResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_internal_proto_plugin_proto_init() }
func file_internal_proto_plugin_proto_init() {
	if File_internal_proto_plugin_proto != nil {
		return
	}
	file_internal_proto_plugin_proto_msgTypes[2].OneofWrappers = []any{
		(*ContentBlock_Text)(nil),
		(*ContentBlock_Image)(nil),
		(*ContentBlock_Json)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_plugin_proto_rawDesc), len(file_internal_proto_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_proto_plugin_proto_goTypes,
		DependencyIndexes: file_internal_proto_plugin_proto_depIdxs,
		EnumInfos:         file_internal_proto_plugin_proto_enumTypes,
		MessageInfos:      file_internal_proto_plugin_proto_msgTypes,
	}.Build()
	File_internal_proto_plugin_proto = out.File
	file_internal_proto_plugin_proto_goTypes = nil
	file_internal_proto_plugin_proto_depIdxs = nil
}
