// Package state persists conversation history as a tree DAG of Entry records.
//
// Each session is a single root Entry with N children forming a tree (every
// entry has exactly one parent, but a parent can have multiple children —
// branches). The leaf entry identifies the "current" position in the tree;
// BuildContext walks backward from the leaf to the root to construct the
// linear context that gets sent to the LLM.
//
// Storage backing is bbolt (one .bolt file per session) with lazy creation:
// the file is not written until the first assistant message is appended, so
// abandoned sessions leave nothing on disk.
package state

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/coevin/tau/internal/llm"
)

// Kind enumerates the supported entry kinds. Each kind has a corresponding
// typed Payload returned by Entry.Payload.
type Kind string

const (
	KindSessionHeader       Kind = "SessionHeader"
	KindMessage             Kind = "Message"
	KindThinkingLevelChange Kind = "ThinkingLevelChange"
	KindModelChange         Kind = "ModelChange"
	KindCompaction          Kind = "Compaction"
	KindBranchSummary       Kind = "BranchSummary"
	KindLabel               Kind = "Label"
	KindSessionInfo         Kind = "SessionInfo"
	KindCustom              Kind = "Custom"
	KindCustomMessage       Kind = "CustomMessage"
	KindClearMarker         Kind = "ClearMarker"
)

// CurrentSchemaVersion is the session-header version this build writes. The
// migration registry (migrate.go) drives older versions forward on Open.
const CurrentSchemaVersion = 1

// Entry is a single node in the session tree DAG. The zero value is not a
// valid entry — always construct via NewEntry or the typed helpers below.
type Entry struct {
	// ID is the 8-hex-character unique identifier for this entry within
	// the session. Generated by idgen.NewID with collision checking.
	ID string `json:"id"`
	// ParentID is the parent entry's ID. Empty for the root entry.
	ParentID string `json:"parentId,omitempty"`
	// Kind names the payload type. Drives payload unmarshaling.
	Kind Kind `json:"kind"`
	// Timestamp records when the entry was appended. Used for ordering
	// and for List displays.
	Timestamp time.Time `json:"timestamp"`
	// Payload is the kind-specific typed data. UnmarshalJSON populates
	// the concrete type based on Kind.
	Payload Payload `json:"payload"`
}

// Payload is the sealed interface for kind-specific entry data. Concrete
// payload types live in this file and all start with the Kind name.
type Payload interface {
	isPayload()
}

// NewEntry constructs an Entry with the given parent and payload, deriving
// Kind from the payload type. ID and Timestamp are zero; callers (Manager /
// store) assign them at append time. NewEntry is mostly for tests; production
// code uses Manager.Append which handles ID + timestamp internally.
func NewEntry(parentID string, payload Payload) Entry {
	return Entry{
		ParentID:  parentID,
		Kind:      kindOf(payload),
		Timestamp: time.Now().UTC(),
		Payload:   payload,
	}
}

// kindOf returns the Kind for a typed payload. Returns KindCustom when the
// payload type is not one of the well-known kinds (callers using CustomPayload
// opt into this fallback intentionally).
func kindOf(p Payload) Kind {
	switch p.(type) {
	case SessionHeaderPayload:
		return KindSessionHeader
	case MessagePayload:
		return KindMessage
	case ThinkingLevelChangePayload:
		return KindThinkingLevelChange
	case ModelChangePayload:
		return KindModelChange
	case CompactionPayload:
		return KindCompaction
	case BranchSummaryPayload:
		return KindBranchSummary
	case LabelPayload:
		return KindLabel
	case SessionInfoPayload:
		return KindSessionInfo
	case CustomPayload:
		return KindCustom
	case CustomMessagePayload:
		return KindCustomMessage
	case ClearMarkerPayload:
		return KindClearMarker
	}
	return KindCustom
}

// --- Concrete payload types ---

// SessionHeaderPayload is the root entry payload. Every session has exactly
// one SessionHeader entry as the root of its tree. Version drives migrations.
type SessionHeaderPayload struct {
	SessionID     string    `json:"sessionId"`
	Cwd           string    `json:"cwd"`
	Model         string    `json:"model,omitempty"`
	Provider      string    `json:"provider,omitempty"`
	Version       int       `json:"version"`
	ParentSession string    `json:"parentSession,omitempty"`
	CreatedAt     time.Time `json:"createdAt"`
}

func (SessionHeaderPayload) isPayload() {}

// MessagePayload carries a conversational message. The Role + Content shape
// mirrors llm.Message exactly; we copy the fields rather than embed so JSON
// marshaling is stable and self-contained.
type MessagePayload struct {
	Role    llm.Role           `json:"role"`
	Content []llm.ContentBlock `json:"content"`
}

func (MessagePayload) isPayload() {}

// MarshalJSON emits MessagePayload with each ContentBlock dispatched to its
// concrete MarshalJSON so the type discriminator is emitted. Without this,
// encoding/json would try to marshal the sealed interface value directly and
// fail.
func (m MessagePayload) MarshalJSON() ([]byte, error) {
	type plain struct {
		Role    llm.Role           `json:"role"`
		Content []llm.ContentBlock `json:"content"`
	}
	return json.Marshal(plain(m))
}

// UnmarshalJSON accepts the shape produced by MarshalJSON, dispatching each
// content element via llm.UnmarshalContentBlock. Mirrors llm.Message's
// unmarshaling so the tagged-union content round-trips identically.
func (m *MessagePayload) UnmarshalJSON(data []byte) error {
	var raw struct {
		Role    llm.Role          `json:"role"`
		Content []json.RawMessage `json:"content"`
	}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	m.Role = raw.Role
	m.Content = make([]llm.ContentBlock, 0, len(raw.Content))
	for _, raw2 := range raw.Content {
		block, err := llm.UnmarshalContentBlock(raw2)
		if err != nil {
			return err
		}
		m.Content = append(m.Content, block)
	}
	return nil
}

// AsMessage converts the payload to an llm.Message.
func (m MessagePayload) AsMessage() llm.Message {
	return llm.Message{Role: m.Role, Content: m.Content}
}

// ThinkingLevelChangePayload records a thinking-level transition.
type ThinkingLevelChangePayload struct {
	Level string `json:"level"`
}

func (ThinkingLevelChangePayload) isPayload() {}

// ModelChangePayload records a model switch mid-session.
type ModelChangePayload struct {
	Model    string `json:"model"`
	Provider string `json:"provider,omitempty"`
}

func (ModelChangePayload) isPayload() {}

// CompactionPayload is appended by the compaction pipeline. FirstKeptEntryID
// is the oldest entry that remains in context after compaction; older entries
// are excluded by BuildContext. Summary is the structured-summary text
// produced by the LLM.
type CompactionPayload struct {
	Summary          string `json:"summary"`
	FirstKeptEntryID string `json:"firstKeptEntryId"`
}

func (CompactionPayload) isPayload() {}

// BranchSummaryPayload is injected (typically by ForkFrom or by an explicit
// /branch command) so that a forked session's context carries a summary of
// the parent branch.
type BranchSummaryPayload struct {
	Summary string `json:"summary"`
}

func (BranchSummaryPayload) isPayload() {}

// LabelPayload tags a single entry with a short label for /tree display and
// /checkout-by-label.
type LabelPayload struct {
	Label string `json:"label"`
}

func (LabelPayload) isPayload() {}

// SessionInfoPayload stores key/value session metadata that does not fit
// any other kind (e.g., exit reason, run duration).
type SessionInfoPayload struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (SessionInfoPayload) isPayload() {}

// CustomPayload carries arbitrary structured data for plugin use. The data
// is preserved through marshal/unmarshal but its shape is opaque to tau.
type CustomPayload struct {
	Type string          `json:"type"`
	Data json.RawMessage `json:"data"`
}

func (CustomPayload) isPayload() {}

// CustomMessagePayload is a Custom variant whose content the LLM should see
// as a message (used by plugins to inject synthetic messages). It differs
// from MessagePayload in that it is not produced by either party in the
// conversation and may carry arbitrary content shapes.
type CustomMessagePayload struct {
	Role    string          `json:"role"`
	Content json.RawMessage `json:"content"`
}

func (CustomMessagePayload) isPayload() {}

// ClearMarkerPayload marks a hard context boundary. Appended by /clear as
// a child of the current leaf. BuildContext truncates the leaf→root walk
// at the first ClearMarker encountered (most-recent first), so subsequent
// turns see an empty history. The marker itself is excluded from the kept
// slice; only entries newer than it (children appended after the clear)
// survive the cutoff.
//
// Recovery: /checkout <oldLeafID> walks from the pre-clear leaf, which
// never reaches the ClearMarker (it's a descendant, not an ancestor), so
// the original context is fully restored.
//
// Reason stores an optional human-readable note (e.g. why /clear was
// invoked). Reserved for future /clear --summarize use; empty today.
type ClearMarkerPayload struct {
	Reason string `json:"reason,omitempty"`
}

func (ClearMarkerPayload) isPayload() {}

// --- JSON marshaling ---

// MarshalJSON serializes Entry as {id, parentId, kind, timestamp, payload}.
// The payload is the concrete typed value, so JSON consumers can decode it
// directly when they know the kind. UnmarshalJSON handles the discriminated
// decode.
func (e Entry) MarshalJSON() ([]byte, error) {
	type wire struct {
		ID        string    `json:"id"`
		ParentID  string    `json:"parentId,omitempty"`
		Kind      Kind      `json:"kind"`
		Timestamp time.Time `json:"timestamp"`
		Payload   Payload   `json:"payload"`
	}
	return json.Marshal(wire(e))
}

// UnmarshalJSON decodes Entry, dispatching on Kind to pick the concrete
// payload type. Unknown kinds decode to CustomPayload so forward-compatible
// reads do not error.
func (e *Entry) UnmarshalJSON(data []byte) error {
	type wire struct {
		ID        string          `json:"id"`
		ParentID  string          `json:"parentId,omitempty"`
		Kind      Kind            `json:"kind"`
		Timestamp time.Time       `json:"timestamp"`
		Payload   json.RawMessage `json:"payload"`
	}
	var w wire
	if err := json.Unmarshal(data, &w); err != nil {
		return fmt.Errorf("state: decode entry: %w", err)
	}
	e.ID = w.ID
	e.ParentID = w.ParentID
	e.Kind = w.Kind
	e.Timestamp = w.Timestamp
	p, err := decodePayload(w.Kind, w.Payload)
	if err != nil {
		return err
	}
	e.Payload = p
	return nil
}

// decodePayload picks the concrete payload type for the given kind and
// unmarshals raw into it. Unknown kinds fall back to CustomPayload. The
// returned Payload always holds a value type (not a pointer) so type
// assertions in callers match the value types they expect.
func decodePayload(kind Kind, raw json.RawMessage) (Payload, error) {
	if len(raw) == 0 || string(raw) == "null" {
		return nil, nil
	}
	switch kind {
	case KindSessionHeader:
		var v SessionHeaderPayload
		if err := json.Unmarshal(raw, &v); err != nil {
			return nil, fmt.Errorf("state: decode %s payload: %w", kind, err)
		}
		return v, nil
	case KindMessage:
		var v MessagePayload
		if err := json.Unmarshal(raw, &v); err != nil {
			return nil, fmt.Errorf("state: decode %s payload: %w", kind, err)
		}
		return v, nil
	case KindThinkingLevelChange:
		var v ThinkingLevelChangePayload
		if err := json.Unmarshal(raw, &v); err != nil {
			return nil, fmt.Errorf("state: decode %s payload: %w", kind, err)
		}
		return v, nil
	case KindModelChange:
		var v ModelChangePayload
		if err := json.Unmarshal(raw, &v); err != nil {
			return nil, fmt.Errorf("state: decode %s payload: %w", kind, err)
		}
		return v, nil
	case KindCompaction:
		var v CompactionPayload
		if err := json.Unmarshal(raw, &v); err != nil {
			return nil, fmt.Errorf("state: decode %s payload: %w", kind, err)
		}
		return v, nil
	case KindBranchSummary:
		var v BranchSummaryPayload
		if err := json.Unmarshal(raw, &v); err != nil {
			return nil, fmt.Errorf("state: decode %s payload: %w", kind, err)
		}
		return v, nil
	case KindLabel:
		var v LabelPayload
		if err := json.Unmarshal(raw, &v); err != nil {
			return nil, fmt.Errorf("state: decode %s payload: %w", kind, err)
		}
		return v, nil
	case KindSessionInfo:
		var v SessionInfoPayload
		if err := json.Unmarshal(raw, &v); err != nil {
			return nil, fmt.Errorf("state: decode %s payload: %w", kind, err)
		}
		return v, nil
	case KindCustom:
		var v CustomPayload
		if err := json.Unmarshal(raw, &v); err != nil {
			return nil, fmt.Errorf("state: decode %s payload: %w", kind, err)
		}
		return v, nil
	case KindCustomMessage:
		var v CustomMessagePayload
		if err := json.Unmarshal(raw, &v); err != nil {
			return nil, fmt.Errorf("state: decode %s payload: %w", kind, err)
		}
		return v, nil
	case KindClearMarker:
		var v ClearMarkerPayload
		if err := json.Unmarshal(raw, &v); err != nil {
			return nil, fmt.Errorf("state: decode %s payload: %w", kind, err)
		}
		return v, nil
	default:
		// Forward-compatible fallback: unknown kind → CustomPayload.
		var c CustomPayload
		if err := json.Unmarshal(raw, &c); err != nil {
			return nil, fmt.Errorf("state: decode unknown payload (kind=%s): %w", kind, err)
		}
		return c, nil
	}
}
